spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dealer
    username: root
    password: Spam123!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
token:
  signing:
    #This key is used as base to generate tokens for authentication
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351